language: node
dist: trusty
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm install
  - npm run lint
  - ng test --code-coverage --single-run
after_success: 'npm run coveralls'
branches:
  only:
    - master
    - develop
